name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FileCounterPro.csproj

    - name: Build and Publish self-contained executable
      run: dotnet publish FileCounterPro.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: FileCounterPro-Windows-App
        path: ./publish/*.exe
