name: Release Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FileCounterPro.csproj

    - name: Build (x64)
      run: dotnet publish FileCounterPro.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish-x64

    - name: Build (ARM64)
      run: dotnet publish FileCounterPro.csproj -c Release -r win-arm64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish-arm64

    - name: Compile Inno Setup Installers
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" installer_x64.iss
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" installer_arm64.iss
      shell: cmd

    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: FileCounterPro Windows (Latest)
        files: |
          ./Installer/FileCounterPro_Setup_x64.exe
          ./Installer/FileCounterPro_Setup_ARM64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
